Add files via upload
NTHU-NLPLAB/nlplab-web pull request #53
Opened 2023-09-26 05:25 UTC by yuchen0816

2023-09-26 08:00 UTC, dspp779 requested changes

2023-09-26 08:00 UTC, dspp779 commented on img/chenchen.jpg
size too big and too high

2023-09-26 08:00 UTC, dspp779 commented on js/members.js
> +            img: 'img/irene.jpg',
`irene123` not `irene`

2023-09-26 08:00 UTC, dspp779 commented on js/members.js
> +            img: 'img/chuchu.jpg',
it's `.jpeg` for the actual file.

2023-09-26 08:00 UTC, dspp779 commented on img/irene123.jpg
size too big

2023-09-26 08:00 UTC, dspp779 commented on js/members.js
> -    ],
should not delete old people🥲

2023-09-26 08:42 UTC, yuchen0816 commented on js/members.js
> +            img: 'img/chuchu.jpg',
change the file name to jpg

2023-09-26 08:43 UTC, yuchen0816 commented on img/chenchen.jpg
update smaller file

2023-09-26 08:43 UTC, yuchen0816 commented on js/members.js
> +            img: 'img/irene.jpg',
irene123

2023-09-26 08:43 UTC, yuchen0816 commented on img/irene123.jpg
update smaller size

2023-09-26 08:44 UTC, yuchen0816 commented on js/members.js
> -    ],
put old people to alumni

2023-09-26 14:02 UTC, dspp779 approved these changes
LGTM

2023-09-27 14:12 UTC, dspp779 approved these changes

2023-09-27 14:12 UTC, merged